<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Model name' => '',
    'ID' => 'ID',
    'Temporary user ID' => 'Временный ID пользователя',
    'User ID' => 'ID пользователя',
    'Created Time' => 'Время создания',
    'Updated Time' => 'Время обновления',
    'Parent element' => 'Материнский элемент',
    'Price' => 'Цена',
    'model' => 'Модель',
    'Hash' => 'Хэш',
    'Cart ID' => 'ID корзины',
    'Item ID' => 'ID элемента',
    'Count' => 'Количество',
    'Description' => 'Описание',
    'Buy' => 'Купить',
    'on' => 'на',
    'Truncate' => 'Очистить',
    'Empty' => 'Пусто',
    'Delete' => 'Удалить',
    'Total' => 'Итого',
    'Cart (<span class="dvizh-cart-price">{p}</span>)' => 'Корзина (<span class="dvizh-cart-price">{p}</span>)',
    'Offer' => 'Оформление',
    'Your cart empty' => 'Ваша корзина пуста',
    'Offer' => 'Оформить',
    'Cart' => 'Корзина',
    'Code' => 'Артикул',
    'Tmp user ID' => 'Временный ID пользователя',
    'Comment' => 'Комментарий',
];
