<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Buy' => 'Pirkti',
    'Cart' => 'Krepšelis',
    'Cart (<span class="dvizh-cart-price">{p}</span>)' => 'Krepšelis (<span class="dvizh-cart-price">{p}</span>)',
    'Cart ID' => 'Krepšelio ID',
    'Count' => 'Kiekis',
    'Created Time' => 'Sukurimo laikas',
    'Hash' => 'Hashas',
    'ID' => 'ID',
    'Item ID' => 'Elemento ID',
    'Model name' => 'Modelio pavadinimas',
    'Offer' => 'Pasiūlymas',
    'Parent element' => 'Tėvinis elementas',
    'Price' => 'Kaina',
    'Tmp user ID' => 'Tmp naudotojo ID',
    'Total' => 'Iš viso',
    'Truncate' => 'Išvalyti',
    'Updated Time' => 'Pakeitimo laikas',
    'User ID' => 'Naudotojo ID',
    'Your cart empty' => 'Jūsų krepšelis tuščias',
    'on' => 'už',
];
